---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: http
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
        - name: http
          image: registry.access.redhat.com/ubi9/httpd-24
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: HTTP_PORT
              value: '8080'
            - name: HTTPS_PORT
              value: '8443'
          imagePullPolicy: Always
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  name: http
spec:
  selector:
    app: http
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: http-lb
spec:
  type: LoadBalancer
  selector:
    app: http
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: http
spec:
  to:
    kind: Service
    name: http
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
